/** Imágenes para tarjetas de ciudad en índices locales y landings. */
const LOCAL_CITY_CARD_IMAGES: Record<string, string> = {
  madrid: "/images/madrid.jpg",
  barcelona: "/images/barcelona.jpg",
  valencia: "/images/valencia.jpg",
  malaga: "/images/malaga.jpg",
  sevilla: "/images/sevilla.jpg",
  bilbao: "/images/bilbao1.jpg",
  zaragoza: "/images/zaragoza.jpg",
  alicante: "/images/valencia1.jpg",
  murcia: "/images/murcia.jpg",
  valladolid: "/images/valladolid.jpg",
  granada: "/images/granada.jpg",
  cordoba: "/images/cordoba.jpg",
  "las-palmas": "/images/laspalmas.jpg",
  oviedo: "/images/oviedo.jpg",
  gijon: "/images/gijon.jpg",
  asturias: "/images/oviedo.jpg",
  vigo: "/images/vigo.jpg",
  santander: "/images/santander.jpg",
  coruna: "/images/coruña.jpg",
  "a-coruna": "/images/coruña.jpg",
  "hospitalet-de-llobregat": "/images/zonas barcelona/hospitalet.jpg",
  "cornella-de-llobregat": "/images/contratos5.jpg",
  badalona: "/images/contratos6.jpg",
  "sant-cugat-del-valles": "/images/zonas barcelona/santjoandespi.jpg",
  sabadell: "/images/barcelona2.jpg",
  terrassa: "/images/contratos7.jpg",
  "les-corts": "/images/livendia-fachada-azul.jpg",
  "barcelona-sants-montjuic": "/images/zonas barcelona/sants.jpg",
  "barcelona-poblenou": "/images/zonas barcelona/poblenou.jpg",
  "barcelona-gotic": "/images/zonas barcelona/ciutatvella.jpg",
  "barcelona-sarria": "/images/zonas barcelona/santgervasi2.jpg",
  "barcelona-born": "/images/zonas barcelona/ciutatvella.jpg",
  "barcelona-barceloneta": "/images/zonas barcelona/barcelona.jpg",
  "barcelona-vila-olimpica": "/images/zonas barcelona/santmarti.jpg",
  "barcelona-el-raval": "/images/zonas barcelona/rabal.jpg",
  "barcelona-eixample": "/images/zonas barcelona/eixample.jpg",
  "barcelona-gracia": "/images/zonas barcelona/gracia.jpg",
  "barcelona-les-corts": "/images/zonas barcelona/barcelona2.jpg",
  "barcelona-sant-marti": "/images/zonas barcelona/santmarti.jpg",
  "barcelona-nou-barris": "/images/barcelona.jpg",
  "barcelona-horta-guinardo": "/images/zonas barcelona/guinardo.jpg",
  "barcelona-sant-andreu": "/images/zonas barcelona/santandreu.jpg",
  castelldefels: "/images/barcelona.jpg",
  "sant-boi-de-llobregat": "/images/barcelona2.jpg",
  gava: "/images/barcelona.jpg",
  "esplugues-de-llobregat": "/images/zonas barcelona/esplugues.jpg",
  "sant-joan-despi": "/images/zonas barcelona/santjoandespi.jpg",
  "sant-adria-de-besos": "/images/barcelona2.jpg",
  "mollet-del-valles": "/images/barcelona2.jpg",
  "barcelona-sarria-sant-gervasi": "/images/zonas barcelona/santgervasi2.jpg",
  "barcelona-ciutat-vella": "/images/zonas barcelona/ciutatvella.jpg",
  mallorca: "/images/mallorca.jpg",
  menorca: "/images/menorca1.jpg",
  palma: "/images/mallorca2.jpg",
};

const FALLBACK_CITY_IMAGE = "/images/tipo2.jpg";

export function getLocalCityCardImage(slug: string): string {
  return LOCAL_CITY_CARD_IMAGES[slug] ?? FALLBACK_CITY_IMAGE;
}
